"""GenOS period reports — daily / weekly / monthly."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from core.env import project_root
from services.generational_os.state import build_system_state, write_system_health, write_system_state

REPORTS_DIR = project_root() / "data" / "generational_os" / "reports"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _write(name: str, body: str) -> Path:
    # Canonical names at data/generational_os/ + archive under reports/
    root = project_root() / "data" / "generational_os"
    root.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    path = root / name
    path.write_text(body, encoding="utf-8")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    (REPORTS_DIR / f"{Path(name).stem}_{stamp}{Path(name).suffix}").write_text(body, encoding="utf-8")
    return path


def generate_daily_report(*, publishing_enabled: bool = False) -> Path:
    state = build_system_state(publishing_enabled=publishing_enabled)
    write_system_state(publishing_enabled=publishing_enabled)
    write_system_health(publishing_enabled=publishing_enabled)
    jobs = state.get("jobs") or {}
    lines = [
        "# DAILY_REPORT",
        "",
        f"**Date:** {_now()[:10]}",
        f"**System health:** {state.get('system_health')}",
        f"**Publishing:** {'enabled' if publishing_enabled else 'disabled'}",
        "",
        "## Operations",
        "",
        f"- Completed: {len(jobs.get('completed') or [])}",
        f"- Queued: {len(jobs.get('queued') or [])}",
        f"- Failed: {len(jobs.get('failed') or [])}",
        f"- Creative Excellence Avg: {state.get('creative_excellence_average')}",
        "",
        "## Top opportunities",
        "",
    ]
    for t in (state.get("trending_opportunities") or [])[:5]:
        lines.append(f"- {t.get('topic')} (score={t.get('score')}, priority={t.get('priority')})")
    lines += [
        "",
        "## Resources",
        "",
        f"- Storage MB: {(state.get('resources') or {}).get('storage_mb')}",
        f"- Est. cost/production USD: {(state.get('resources') or {}).get('estimated_cost_per_production_usd')}",
        f"- ElevenLabs configured: {((state.get('resources') or {}).get('elevenlabs') or {}).get('configured')}",
        "",
        "## Failures requiring intervention",
        "",
    ]
    failed = jobs.get("failed") or []
    if not failed:
        lines.append("_None._")
    for f in failed[:10]:
        lines.append(f"- {f.get('topic')}: {f.get('error') or (f.get('classification') or {}).get('class')}")
    lines += ["", "_Generated by GenOS._", ""]
    return _write("DAILY_REPORT.md", "\n".join(lines))


def generate_weekly_report(*, publishing_enabled: bool = False) -> Path:
    state = build_system_state(publishing_enabled=publishing_enabled)
    from services.generational_os.learning_store import list_lessons

    lessons = list_lessons(50)
    week_ago = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()
    recent = [l for l in lessons if str(l.get("recorded_at") or "") >= week_ago]
    lines = [
        "# WEEKLY_REPORT",
        "",
        f"**Generated:** {_now()}",
        f"**System health:** {state.get('system_health')}",
        "",
        f"## Lessons this week: {len(recent)}",
        "",
    ]
    for l in recent[:15]:
        lines.append(f"- **{l.get('topic')}** — {l.get('highest_impact_lesson')}")
    lines += [
        "",
        f"Creative excellence average: {state.get('creative_excellence_average')}",
        f"Departments available: {(state.get('department_health') or {}).get('available_count')}/{(state.get('department_health') or {}).get('total')}",
        "",
        "_Generated by GenOS._",
        "",
    ]
    return _write("WEEKLY_REPORT.md", "\n".join(lines))


def generate_monthly_report(*, publishing_enabled: bool = False) -> Path:
    state = build_system_state(publishing_enabled=publishing_enabled)
    from services.generational_os.learning_store import list_lessons

    lessons = list_lessons(200)
    lines = [
        "# MONTHLY_REPORT",
        "",
        f"**Generated:** {_now()}",
        "",
        "## OS snapshot",
        "",
        f"- Health: {state.get('system_health')}",
        f"- Throughput est./day: {(state.get('estimated_throughput') or {}).get('estimated_productions_per_day')}",
        f"- Total lessons stored: {len(lessons)}",
        f"- Estimated operating cost/production: ${(state.get('resources') or {}).get('estimated_cost_per_production_usd')}",
        "",
        "## Strategic notes",
        "",
        "- Continue ranking Science opportunities via Trend Intelligence.",
        "- Keep publishing disabled until Creative Excellence floor is met.",
        "- Feed Audience Intelligence lessons into next Briefs automatically.",
        "",
        "_Generated by GenOS._",
        "",
    ]
    return _write("MONTHLY_REPORT.md", "\n".join(lines))


def generate_all_reports(*, publishing_enabled: bool = False) -> dict[str, str]:
    return {
        "DAILY_REPORT.md": str(generate_daily_report(publishing_enabled=publishing_enabled)),
        "WEEKLY_REPORT.md": str(generate_weekly_report(publishing_enabled=publishing_enabled)),
        "MONTHLY_REPORT.md": str(generate_monthly_report(publishing_enabled=publishing_enabled)),
        "SYSTEM_HEALTH.md": str(write_system_health(publishing_enabled=publishing_enabled)),
        "SYSTEM_STATE.json": str(write_system_state(publishing_enabled=publishing_enabled)),
        "PRODUCTION_QUEUE.json": str(project_root() / "data" / "generational_os" / "PRODUCTION_QUEUE.json"),
    }
