"""DOCTOR_001 — permanent library catalogs (expressions, hands, animations)."""

from __future__ import annotations

CHARACTER_ID = "DOCTOR_001"
LEGACY_ALIAS = "CHAR-0001"
ASSET_SLUG = "DOCTOR_001"
DISPLAY_NAME = "The Doctor"
ASSET_VERSION = "1.1.0"

# 50+ locked facial expressions — permanent library, not episode one-offs.
EXPRESSIONS: list[str] = [
    # baseline
    "neutral",
    "calm",
    "clinical_neutral",
    "bedside_warm",
    # positive
    "soft_smile",
    "warm_smile",
    "broad_smile",
    "happy",
    "joyful",
    "laughing",
    "amused",
    "delighted",
    "hopeful",
    "proud",
    "energized",
    # curiosity / cognition
    "curious",
    "intrigued",
    "fascinated",
    "wondering",
    "puzzled",
    "confused_soft",
    "thoughtful",
    "contemplative",
    "reflecting",
    "analyzing",
    "skeptical",
    "doubtful",
    # teaching / care
    "teaching",
    "explaining",
    "clarifying",
    "emphasizing",
    "reassuring",
    "encouraging",
    "supportive",
    "compassionate",
    "caring",
    "gentle",
    "patient",
    "listening",
    "attentive",
    "waiting",
    # concern / resolve
    "concerned",
    "worried_soft",
    "serious",
    "focused",
    "concentrated",
    "determined",
    "confident",
    "assured",
    "solemn",
    "tired_soft",
    # surprise / eyes
    "surprised",
    "amazed",
    "awe",
    "startled_soft",
    "eyes_half",
    "eyes_wide",
    "brows_raised",
    "brows_knit",
    "blink",
    "wink_soft",
    # micro / speech
    "micro_doubt",
    "micro_approval",
    "lip_press",
    "open_mouth_speak",
    "viseme_AA",
    "viseme_E",
    "viseme_O",
    "viseme_U",
    "viseme_MBP",
]

assert len(EXPRESSIONS) >= 50

# Map library expressions → renderer family used by plate draw.
EXPRESSION_FAMILY: dict[str, str] = {
    "neutral": "neutral",
    "calm": "neutral",
    "clinical_neutral": "neutral",
    "bedside_warm": "smiling",
    "soft_smile": "smiling",
    "warm_smile": "smiling",
    "broad_smile": "happy",
    "happy": "happy",
    "joyful": "happy",
    "laughing": "laughing",
    "amused": "smiling",
    "delighted": "excited",
    "hopeful": "smiling",
    "proud": "confident",
    "energized": "excited",
    "curious": "curious",
    "intrigued": "curious",
    "fascinated": "curious",
    "wondering": "curious",
    "puzzled": "thinking",
    "confused_soft": "thinking",
    "thoughtful": "thinking",
    "contemplative": "thinking",
    "reflecting": "thinking",
    "analyzing": "focused",
    "skeptical": "serious",
    "doubtful": "concerned",
    "teaching": "teaching",
    "explaining": "teaching",
    "clarifying": "teaching",
    "emphasizing": "confident",
    "reassuring": "smiling",
    "encouraging": "smiling",
    "supportive": "smiling",
    "compassionate": "smiling",
    "caring": "smiling",
    "gentle": "smiling",
    "patient": "listening",
    "listening": "listening",
    "attentive": "listening",
    "waiting": "neutral",
    "concerned": "concerned",
    "worried_soft": "concerned",
    "serious": "serious",
    "focused": "focused",
    "concentrated": "focused",
    "determined": "confident",
    "confident": "confident",
    "assured": "confident",
    "solemn": "serious",
    "tired_soft": "neutral",
    "surprised": "surprised",
    "amazed": "surprised",
    "awe": "surprised",
    "startled_soft": "surprised",
    "eyes_half": "neutral",
    "eyes_wide": "surprised",
    "brows_raised": "curious",
    "brows_knit": "concerned",
    "blink": "blink",
    "wink_soft": "smiling",
    "micro_doubt": "thinking",
    "micro_approval": "smiling",
    "lip_press": "serious",
    "open_mouth_speak": "surprised",
    "viseme_AA": "surprised",
    "viseme_E": "teaching",
    "viseme_O": "surprised",
    "viseme_U": "thinking",
    "viseme_MBP": "serious",
}

ORTHOGRAPHIC_VIEWS = ["front", "side_left", "side_right", "back", "three_quarter"]

HAND_POSES = [
    "relaxed_open",
    "soft_fist",
    "point_index",
    "point_two_finger",
    "open_palm_up",
    "open_palm_forward",
    "pinch_precision",
    "grip_scanner",
    "grip_clipboard",
    "thumbs_measure",
    "cup_hands",
    "heart_height_open",
    "ok_reassure",
    "stop_gentle",
    "diagram_trace",
    "hologram_pinch",
    "typing_rest",
    "behind_back",
]

CORE_ANIMATIONS = [
    "idle",
    "breathing",
    "blinking",
    "walking_cycle",
    "running_cycle",
    "talking",
    "pointing",
    "teaching",
    "listening",
    "turning",
    "stopping",
    "greeting",
    "explaining",
    "looking_around",
    "picking_up_objects",
    "interacting_with_equipment",
    "holding_medical_scanner",
    "using_holograms",
    "typing",
]

REACTION_ANIMATIONS = [
    "reaction_curiosity",
    "reaction_concern",
    "reaction_delight",
    "reaction_surprise",
    "reaction_compassion",
    "reaction_determination",
    "reaction_amusement",
    "reaction_realization",
]

CAMERA_TESTS = [
    "closeup_eyes",
    "closeup_face",
    "medium_bust",
    "full_body_hero",
    "silhouette_readability",
    "over_shoulder_teach",
    "profile_listen",
    "low_angle_authority",
    "high_angle_gentle",
    "practical_rim_clinical",
]

ENVIRONMENT_INTERACTIONS = [
    "touch_console",
    "open_door",
    "lift_scanner",
    "place_clipboard",
    "gesture_to_hologram",
    "walk_corridor",
    "sit_exam_stool",
    "stand_at_bedside",
]

LIGHTING_REFS = [
    "day_teach_soft_key",
    "night_research_cool_rim",
    "emergency_alert_red_practical",
    "theater_holo_blue",
    "garden_walk_golden",
    "closeup_beauty_clinical",
]
