"""Sprint Wave 6 — final remaining-time push."""
from __future__ import annotations
import importlib.util, json, sys, time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from core.env import load_application_env
load_application_env()
_spec = importlib.util.spec_from_file_location("sprint_100min_batch", ROOT / "scripts" / "sprint_100min_batch.py")
_batch = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(_batch)
MAX_WORKERS = 3
REPORT_DIR = _batch.REPORT_DIR
aggregate = _batch.aggregate
run_one = _batch.run_one
_seo_score = _batch._seo_score
from services.media_production import ffmpeg_available
from services.provider_runtime.config import has_credential
BUDGET_MIN = float(sys.argv[1]) if len(sys.argv) > 1 else 20.0
TOPICS = []
TOPICS.append({'asset_id': 'sp100w6_000_photosystem_ii_001', 'title': 'Photosystem II', 'hook': 'Clear science on photosystem II — without the viral shortcuts.', 'description': 'Explain photosystem II accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['photosystem II'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Photosystem II', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_001_calvin_cycle_001', 'title': 'Calvin cycle', 'hook': 'Clear science on Calvin cycle — without the viral shortcuts.', 'description': 'Explain Calvin cycle accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Calvin cycle'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Calvin cycle', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_002_krebs_cycle_001', 'title': 'Krebs cycle', 'hook': 'Clear science on Krebs cycle — without the viral shortcuts.', 'description': 'Explain Krebs cycle accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Krebs cycle'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Krebs cycle', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_003_glycolysis_basics_001', 'title': 'Glycolysis basics', 'hook': 'Clear science on glycolysis basics — without the viral shortcuts.', 'description': 'Explain glycolysis basics accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['glycolysis basics'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Glycolysis basics', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_004_electron_transport_chain_001', 'title': 'Electron transport chain', 'hook': 'Clear science on electron transport chain — without the viral shortcuts.', 'description': 'Explain electron transport chain accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['electron transport chain'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Electron transport chain', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_005_chemiosmosis_001', 'title': 'Chemiosmosis', 'hook': 'Clear science on chemiosmosis — without the viral shortcuts.', 'description': 'Explain chemiosmosis accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['chemiosmosis'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Chemiosmosis', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_006_nadh_role_001', 'title': 'NADH role', 'hook': 'Clear science on NADH role — without the viral shortcuts.', 'description': 'Explain NADH role accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['NADH role'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'NADH role', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_007_fadh2_role_001', 'title': 'FADH2 role', 'hook': 'Clear science on FADH2 role — without the viral shortcuts.', 'description': 'Explain FADH2 role accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['FADH2 role'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'FADH2 role', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_008_oxidative_phosphorylation_001', 'title': 'Oxidative phosphorylation', 'hook': 'Clear science on oxidative phosphorylation — without the viral shortcuts.', 'description': 'Explain oxidative phosphorylation accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['oxidative phosphorylation'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Oxidative phosphorylation', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_009_fermentation_lactate_001', 'title': 'Fermentation lactate', 'hook': 'Clear science on fermentation lactate — without the viral shortcuts.', 'description': 'Explain fermentation lactate accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['fermentation lactate'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Fermentation lactate', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_010_alcoholic_fermentation_001', 'title': 'Alcoholic fermentation', 'hook': 'Clear science on alcoholic fermentation — without the viral shortcuts.', 'description': 'Explain alcoholic fermentation accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['alcoholic fermentation'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Alcoholic fermentation', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_011_stomata_gas_exchange_001', 'title': 'Stomata gas exchange', 'hook': 'Clear science on stomata gas exchange — without the viral shortcuts.', 'description': 'Explain stomata gas exchange accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['stomata gas exchange'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Stomata gas exchange', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_012_xylem_transport_001', 'title': 'Xylem transport', 'hook': 'Clear science on xylem transport — without the viral shortcuts.', 'description': 'Explain xylem transport accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['xylem transport'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Xylem transport', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_013_phloem_transport_001', 'title': 'Phloem transport', 'hook': 'Clear science on phloem transport — without the viral shortcuts.', 'description': 'Explain phloem transport accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['phloem transport'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Phloem transport', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_014_transpiration_pull_001', 'title': 'Transpiration pull', 'hook': 'Clear science on transpiration pull — without the viral shortcuts.', 'description': 'Explain transpiration pull accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['transpiration pull'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Transpiration pull', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_015_capillary_action_plants_001', 'title': 'Capillary action plants', 'hook': 'Clear science on capillary action plants — without the viral shortcuts.', 'description': 'Explain capillary action plants accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['capillary action plants'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Capillary action plants', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_016_root_nodules_nitrogen_001', 'title': 'Root nodules nitrogen', 'hook': 'Clear science on root nodules nitrogen — without the viral shortcuts.', 'description': 'Explain root nodules nitrogen accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['root nodules nitrogen'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Root nodules nitrogen', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_017_nitrogen_fixation_bacteria_001', 'title': 'Nitrogen fixation bacteria', 'hook': 'Clear science on nitrogen fixation bacteria — without the viral shortcuts.', 'description': 'Explain nitrogen fixation bacteria accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['nitrogen fixation bacteria'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Nitrogen fixation bacteria', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_018_mycorrhizae_nutrient_trade_001', 'title': 'Mycorrhizae nutrient trade', 'hook': 'Clear science on mycorrhizae nutrient trade — without the viral shortcuts.', 'description': 'Explain mycorrhizae nutrient trade accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['mycorrhizae nutrient trade'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Mycorrhizae nutrient trade', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_019_lichen_symbiosis_001', 'title': 'Lichen symbiosis', 'hook': 'Clear science on lichen symbiosis — without the viral shortcuts.', 'description': 'Explain lichen symbiosis accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['lichen symbiosis'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Lichen symbiosis', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_020_pollination_syndromes_001', 'title': 'Pollination syndromes', 'hook': 'Clear science on pollination syndromes — without the viral shortcuts.', 'description': 'Explain pollination syndromes accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['pollination syndromes'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Pollination syndromes', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_021_seed_dispersal_strategies_001', 'title': 'Seed dispersal strategies', 'hook': 'Clear science on seed dispersal strategies — without the viral shortcuts.', 'description': 'Explain seed dispersal strategies accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['seed dispersal strategies'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Seed dispersal strategies', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_022_camouflage_evolution_001', 'title': 'Camouflage evolution', 'hook': 'Clear science on camouflage evolution — without the viral shortcuts.', 'description': 'Explain camouflage evolution accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['camouflage evolution'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Camouflage evolution', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_023_aposematism_warning_colors_001', 'title': 'Aposematism warning colors', 'hook': 'Clear science on aposematism warning colors — without the viral shortcuts.', 'description': 'Explain aposematism warning colors accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['aposematism warning colors'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Aposematism warning colors', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_024_batesian_mimicry_001', 'title': 'Batesian mimicry', 'hook': 'Clear science on Batesian mimicry — without the viral shortcuts.', 'description': 'Explain Batesian mimicry accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Batesian mimicry'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Batesian mimicry', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_025_mullerian_mimicry_001', 'title': 'Mullerian mimicry', 'hook': 'Clear science on Mullerian mimicry — without the viral shortcuts.', 'description': 'Explain Mullerian mimicry accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Mullerian mimicry'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Mullerian mimicry', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_026_sexual_selection_peacocks_001', 'title': 'Sexual selection peacocks', 'hook': 'Clear science on sexual selection peacocks — without the viral shortcuts.', 'description': 'Explain sexual selection peacocks accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['sexual selection peacocks'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Sexual selection peacocks', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_027_handicap_principle_001', 'title': 'Handicap principle', 'hook': 'Clear science on handicap principle — without the viral shortcuts.', 'description': 'Explain handicap principle accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['handicap principle'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Handicap principle', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_028_kin_selection_001', 'title': 'Kin selection', 'hook': 'Clear science on kin selection — without the viral shortcuts.', 'description': 'Explain kin selection accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['kin selection'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Kin selection', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_029_reciprocal_altruism_001', 'title': 'Reciprocal altruism', 'hook': 'Clear science on reciprocal altruism — without the viral shortcuts.', 'description': 'Explain reciprocal altruism accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['reciprocal altruism'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Reciprocal altruism', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_030_hamilton_rule_idea_001', 'title': 'Hamilton rule idea', 'hook': 'Clear science on Hamilton rule idea — without the viral shortcuts.', 'description': 'Explain Hamilton rule idea accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Hamilton rule idea'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Hamilton rule idea', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_031_inclusive_fitness_001', 'title': 'Inclusive fitness', 'hook': 'Clear science on inclusive fitness — without the viral shortcuts.', 'description': 'Explain inclusive fitness accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['inclusive fitness'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Inclusive fitness', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_032_evolutionary_stable_strategy_001', 'title': 'Evolutionary stable strategy', 'hook': 'Clear science on evolutionary stable strategy — without the viral shortcuts.', 'description': 'Explain evolutionary stable strategy accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['evolutionary stable strategy'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Evolutionary stable strategy', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_033_red_queen_hypothesis_001', 'title': 'Red Queen hypothesis', 'hook': 'Clear science on Red Queen hypothesis — without the viral shortcuts.', 'description': 'Explain Red Queen hypothesis accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Red Queen hypothesis'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Red Queen hypothesis', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_034_punctuated_equilibrium_001', 'title': 'Punctuated equilibrium', 'hook': 'Clear science on punctuated equilibrium — without the viral shortcuts.', 'description': 'Explain punctuated equilibrium accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['punctuated equilibrium'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Punctuated equilibrium', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_035_gradualism_evolution_001', 'title': 'Gradualism evolution', 'hook': 'Clear science on gradualism evolution — without the viral shortcuts.', 'description': 'Explain gradualism evolution accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['gradualism evolution'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Gradualism evolution', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_036_speciation_allopatric_001', 'title': 'Speciation allopatric', 'hook': 'Clear science on speciation allopatric — without the viral shortcuts.', 'description': 'Explain speciation allopatric accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['speciation allopatric'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Speciation allopatric', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_037_sympatric_speciation_debate_001', 'title': 'Sympatric speciation debate', 'hook': 'Clear science on sympatric speciation debate — without the viral shortcuts.', 'description': 'Explain sympatric speciation debate accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['sympatric speciation debate'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Sympatric speciation debate', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_038_ring_species_001', 'title': 'Ring species', 'hook': 'Clear science on ring species — without the viral shortcuts.', 'description': 'Explain ring species accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['ring species'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Ring species', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_039_founder_effect_001', 'title': 'Founder effect', 'hook': 'Clear science on founder effect — without the viral shortcuts.', 'description': 'Explain founder effect accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['founder effect'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Founder effect', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_040_bottleneck_effect_001', 'title': 'Bottleneck effect', 'hook': 'Clear science on bottleneck effect — without the viral shortcuts.', 'description': 'Explain bottleneck effect accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['bottleneck effect'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Bottleneck effect', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_041_genetic_drift_001', 'title': 'Genetic drift', 'hook': 'Clear science on genetic drift — without the viral shortcuts.', 'description': 'Explain genetic drift accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['genetic drift'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Genetic drift', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_042_hardy_weinberg_idea_001', 'title': 'Hardy Weinberg idea', 'hook': 'Clear science on Hardy Weinberg idea — without the viral shortcuts.', 'description': 'Explain Hardy Weinberg idea accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Hardy Weinberg idea'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Hardy Weinberg idea', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_043_assortative_mating_001', 'title': 'Assortative mating', 'hook': 'Clear science on assortative mating — without the viral shortcuts.', 'description': 'Explain assortative mating accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['assortative mating'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Assortative mating', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_044_sexual_dimorphism_001', 'title': 'Sexual dimorphism', 'hook': 'Clear science on sexual dimorphism — without the viral shortcuts.', 'description': 'Explain sexual dimorphism accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['sexual dimorphism'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Sexual dimorphism', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_045_parental_investment_theory_001', 'title': 'Parental investment theory', 'hook': 'Clear science on parental investment theory — without the viral shortcuts.', 'description': 'Explain parental investment theory accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['parental investment theory'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Parental investment theory', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_046_life_history_tradeoffs_001', 'title': 'Life history tradeoffs', 'hook': 'Clear science on life history tradeoffs — without the viral shortcuts.', 'description': 'Explain life history tradeoffs accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['life history tradeoffs'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Life history tradeoffs', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_047_r_vs_k_selection_nuance_001', 'title': 'R vs K selection nuance', 'hook': 'Clear science on r vs K selection nuance — without the viral shortcuts.', 'description': 'Explain r vs K selection nuance accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['r vs K selection nuance'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'R vs K selection nuance', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_048_island_biogeography_001', 'title': 'Island biogeography', 'hook': 'Clear science on island biogeography — without the viral shortcuts.', 'description': 'Explain island biogeography accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['island biogeography'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Island biogeography', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_049_edge_effects_habitat_001', 'title': 'Edge effects habitat', 'hook': 'Clear science on edge effects habitat — without the viral shortcuts.', 'description': 'Explain edge effects habitat accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['edge effects habitat'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Edge effects habitat', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_050_trophic_cascades_001', 'title': 'Trophic cascades', 'hook': 'Clear science on trophic cascades — without the viral shortcuts.', 'description': 'Explain trophic cascades accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['trophic cascades'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Trophic cascades', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_051_apex_predators_role_001', 'title': 'Apex predators role', 'hook': 'Clear science on apex predators role — without the viral shortcuts.', 'description': 'Explain apex predators role accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['apex predators role'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Apex predators role', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_052_mesopredator_release_001', 'title': 'Mesopredator release', 'hook': 'Clear science on mesopredator release — without the viral shortcuts.', 'description': 'Explain mesopredator release accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['mesopredator release'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Mesopredator release', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_053_invasive_species_dynamics_001', 'title': 'Invasive species dynamics', 'hook': 'Clear science on invasive species dynamics — without the viral shortcuts.', 'description': 'Explain invasive species dynamics accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['invasive species dynamics'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Invasive species dynamics', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_054_eutrophication_001', 'title': 'Eutrophication', 'hook': 'Clear science on eutrophication — without the viral shortcuts.', 'description': 'Explain eutrophication accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['eutrophication'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Eutrophication', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_055_dead_zones_ocean_001', 'title': 'Dead zones ocean', 'hook': 'Clear science on dead zones ocean — without the viral shortcuts.', 'description': 'Explain dead zones ocean accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['dead zones ocean'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Dead zones ocean', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_056_hypoxia_aquatic_001', 'title': 'Hypoxia aquatic', 'hook': 'Clear science on hypoxia aquatic — without the viral shortcuts.', 'description': 'Explain hypoxia aquatic accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['hypoxia aquatic'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Hypoxia aquatic', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_057_bioaccumulation_001', 'title': 'Bioaccumulation', 'hook': 'Clear science on bioaccumulation — without the viral shortcuts.', 'description': 'Explain bioaccumulation accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['bioaccumulation'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Bioaccumulation', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_058_biomagnification_001', 'title': 'Biomagnification', 'hook': 'Clear science on biomagnification — without the viral shortcuts.', 'description': 'Explain biomagnification accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['biomagnification'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Biomagnification', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_059_ddt_history_lesson_001', 'title': 'DDT history lesson', 'hook': 'Clear science on DDT history lesson — without the viral shortcuts.', 'description': 'Explain DDT history lesson accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['DDT history lesson'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'DDT history lesson', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_060_silent_spring_legacy_001', 'title': 'Silent Spring legacy', 'hook': 'Clear science on Silent Spring legacy — without the viral shortcuts.', 'description': 'Explain Silent Spring legacy accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Silent Spring legacy'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Silent Spring legacy', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_061_conservation_triage_001', 'title': 'Conservation triage', 'hook': 'Clear science on conservation triage — without the viral shortcuts.', 'description': 'Explain conservation triage accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['conservation triage'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Conservation triage', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_062_rewilding_debates_001', 'title': 'Rewilding debates', 'hook': 'Clear science on rewilding debates — without the viral shortcuts.', 'description': 'Explain rewilding debates accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['rewilding debates'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Rewilding debates', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_063_corridor_ecology_001', 'title': 'Corridor ecology', 'hook': 'Clear science on corridor ecology — without the viral shortcuts.', 'description': 'Explain corridor ecology accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['corridor ecology'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Corridor ecology', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_064_umbrella_species_001', 'title': 'Umbrella species', 'hook': 'Clear science on umbrella species — without the viral shortcuts.', 'description': 'Explain umbrella species accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['umbrella species'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Umbrella species', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_065_flagship_species_001', 'title': 'Flagship species', 'hook': 'Clear science on flagship species — without the viral shortcuts.', 'description': 'Explain flagship species accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['flagship species'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Flagship species', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_066_ex_situ_conservation_001', 'title': 'Ex situ conservation', 'hook': 'Clear science on ex situ conservation — without the viral shortcuts.', 'description': 'Explain ex situ conservation accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['ex situ conservation'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Ex situ conservation', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_067_seed_banks_001', 'title': 'Seed banks', 'hook': 'Clear science on seed banks — without the viral shortcuts.', 'description': 'Explain seed banks accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['seed banks'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Seed banks', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_068_cryopreservation_wildlife_001', 'title': 'Cryopreservation wildlife', 'hook': 'Clear science on cryopreservation wildlife — without the viral shortcuts.', 'description': 'Explain cryopreservation wildlife accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['cryopreservation wildlife'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Cryopreservation wildlife', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_069_de_extinction_limits_001', 'title': 'De-extinction limits', 'hook': 'Clear science on de-extinction limits — without the viral shortcuts.', 'description': 'Explain de-extinction limits accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['de-extinction limits'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'De-extinction limits', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_070_synthetic_biology_intro_001', 'title': 'Synthetic biology intro', 'hook': 'Clear science on synthetic biology intro — without the viral shortcuts.', 'description': 'Explain synthetic biology intro accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['synthetic biology intro'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Synthetic biology intro', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_071_biobricks_idea_001', 'title': 'Biobricks idea', 'hook': 'Clear science on biobricks idea — without the viral shortcuts.', 'description': 'Explain biobricks idea accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['biobricks idea'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Biobricks idea', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_072_minimal_genome_001', 'title': 'Minimal genome', 'hook': 'Clear science on minimal genome — without the viral shortcuts.', 'description': 'Explain minimal genome accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['minimal genome'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Minimal genome', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_073_xenobiology_caution_001', 'title': 'Xenobiology caution', 'hook': 'Clear science on xenobiology caution — without the viral shortcuts.', 'description': 'Explain xenobiology caution accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['xenobiology caution'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Xenobiology caution', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_074_organoids_research_001', 'title': 'Organoids research', 'hook': 'Clear science on organoids research — without the viral shortcuts.', 'description': 'Explain organoids research accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['organoids research'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Organoids research', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_075_organs_on_chips_001', 'title': 'Organs on chips', 'hook': 'Clear science on organs on chips — without the viral shortcuts.', 'description': 'Explain organs on chips accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['organs on chips'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Organs on chips', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_076_3d_bioprinting_limits_001', 'title': '3D bioprinting limits', 'hook': 'Clear science on 3D bioprinting limits — without the viral shortcuts.', 'description': 'Explain 3D bioprinting limits accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['3D bioprinting limits'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + '3D bioprinting limits', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_077_xenotransplantation_progress_001', 'title': 'Xenotransplantation progress', 'hook': 'Clear science on xenotransplantation progress — without the viral shortcuts.', 'description': 'Explain xenotransplantation progress accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['xenotransplantation progress'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Xenotransplantation progress', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_078_blood_type_genetics_001', 'title': 'Blood type genetics', 'hook': 'Clear science on blood type genetics — without the viral shortcuts.', 'description': 'Explain blood type genetics accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['blood type genetics'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Blood type genetics', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_079_rh_factor_001', 'title': 'Rh factor', 'hook': 'Clear science on Rh factor — without the viral shortcuts.', 'description': 'Explain Rh factor accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['Rh factor'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Rh factor', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_080_universal_donor_myth_nuance_001', 'title': 'Universal donor myth nuance', 'hook': 'Clear science on universal donor myth nuance — without the viral shortcuts.', 'description': 'Explain universal donor myth nuance accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['universal donor myth nuance'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Universal donor myth nuance', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_081_plasma_vs_serum_001', 'title': 'Plasma vs serum', 'hook': 'Clear science on plasma vs serum — without the viral shortcuts.', 'description': 'Explain plasma vs serum accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['plasma vs serum'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Plasma vs serum', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_082_ecg_basics_001', 'title': 'ECG basics', 'hook': 'Clear science on ECG basics — without the viral shortcuts.', 'description': 'Explain ECG basics accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['ECG basics'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'ECG basics', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_083_heart_valves_001', 'title': 'Heart valves', 'hook': 'Clear science on heart valves — without the viral shortcuts.', 'description': 'Explain heart valves accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['heart valves'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Heart valves', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_084_cardiac_output_001', 'title': 'Cardiac output', 'hook': 'Clear science on cardiac output — without the viral shortcuts.', 'description': 'Explain cardiac output accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['cardiac output'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Cardiac output', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_085_blood_pressure_regulation_001', 'title': 'Blood pressure regulation', 'hook': 'Clear science on blood pressure regulation — without the viral shortcuts.', 'description': 'Explain blood pressure regulation accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['blood pressure regulation'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Blood pressure regulation', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_086_baroreceptors_001', 'title': 'Baroreceptors', 'hook': 'Clear science on baroreceptors — without the viral shortcuts.', 'description': 'Explain baroreceptors accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['baroreceptors'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Baroreceptors', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_087_kidney_renin_angiotensin_001', 'title': 'Kidney renin angiotensin', 'hook': 'Clear science on kidney renin angiotensin — without the viral shortcuts.', 'description': 'Explain kidney renin angiotensin accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['kidney renin angiotensin'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Kidney renin angiotensin', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_088_adh_water_balance_001', 'title': 'ADH water balance', 'hook': 'Clear science on ADH water balance — without the viral shortcuts.', 'description': 'Explain ADH water balance accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['ADH water balance'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'ADH water balance', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_089_aldosterone_sodium_001', 'title': 'Aldosterone sodium', 'hook': 'Clear science on aldosterone sodium — without the viral shortcuts.', 'description': 'Explain aldosterone sodium accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['aldosterone sodium'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Aldosterone sodium', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_090_thermoregulation_001', 'title': 'Thermoregulation', 'hook': 'Clear science on thermoregulation — without the viral shortcuts.', 'description': 'Explain thermoregulation accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['thermoregulation'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Thermoregulation', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_091_brown_fat_001', 'title': 'Brown fat', 'hook': 'Clear science on brown fat — without the viral shortcuts.', 'description': 'Explain brown fat accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['brown fat'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Brown fat', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_092_shivering_thermogenesis_001', 'title': 'Shivering thermogenesis', 'hook': 'Clear science on shivering thermogenesis — without the viral shortcuts.', 'description': 'Explain shivering thermogenesis accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['shivering thermogenesis'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Shivering thermogenesis', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_093_acclimatization_altitude_001', 'title': 'Acclimatization altitude', 'hook': 'Clear science on acclimatization altitude — without the viral shortcuts.', 'description': 'Explain acclimatization altitude accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['acclimatization altitude'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Acclimatization altitude', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_094_epo_altitude_001', 'title': 'EPO altitude', 'hook': 'Clear science on EPO altitude — without the viral shortcuts.', 'description': 'Explain EPO altitude accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['EPO altitude'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'EPO altitude', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_095_diving_reflex_001', 'title': 'Diving reflex', 'hook': 'Clear science on diving reflex — without the viral shortcuts.', 'description': 'Explain diving reflex accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['diving reflex'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Diving reflex', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_096_nitrogen_narcosis_001', 'title': 'Nitrogen narcosis', 'hook': 'Clear science on nitrogen narcosis — without the viral shortcuts.', 'description': 'Explain nitrogen narcosis accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['nitrogen narcosis'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Nitrogen narcosis', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_097_decompression_sickness_001', 'title': 'Decompression sickness', 'hook': 'Clear science on decompression sickness — without the viral shortcuts.', 'description': 'Explain decompression sickness accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['decompression sickness'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Decompression sickness', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_098_sonar_whales_anthropogenic_001', 'title': 'Sonar whales anthropogenic', 'hook': 'Clear science on sonar whales anthropogenic — without the viral shortcuts.', 'description': 'Explain sonar whales anthropogenic accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['sonar whales anthropogenic'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Sonar whales anthropogenic', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_099_ship_noise_ocean_001', 'title': 'Ship noise ocean', 'hook': 'Clear science on ship noise ocean — without the viral shortcuts.', 'description': 'Explain ship noise ocean accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['ship noise ocean'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Ship noise ocean', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_100_coral_microbiome_001', 'title': 'Coral microbiome', 'hook': 'Clear science on coral microbiome — without the viral shortcuts.', 'description': 'Explain coral microbiome accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['coral microbiome'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Coral microbiome', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_101_sponge_reefs_001', 'title': 'Sponge reefs', 'hook': 'Clear science on sponge reefs — without the viral shortcuts.', 'description': 'Explain sponge reefs accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['sponge reefs'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Sponge reefs', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_102_kelp_forests_001', 'title': 'Kelp forests', 'hook': 'Clear science on kelp forests — without the viral shortcuts.', 'description': 'Explain kelp forests accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['kelp forests'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Kelp forests', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_103_mangrove_carbon_001', 'title': 'Mangrove carbon', 'hook': 'Clear science on mangrove carbon — without the viral shortcuts.', 'description': 'Explain mangrove carbon accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['mangrove carbon'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Mangrove carbon', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_104_seagrass_meadows_001', 'title': 'Seagrass meadows', 'hook': 'Clear science on seagrass meadows — without the viral shortcuts.', 'description': 'Explain seagrass meadows accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['seagrass meadows'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Seagrass meadows', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})
TOPICS.append({'asset_id': 'sp100w6_105_blue_carbon_001', 'title': 'Blue carbon', 'hook': 'Clear science on blue carbon — without the viral shortcuts.', 'description': 'Explain blue carbon accurately for a general audience. Flag uncertainty. No sensationalism.', 'hashtags': ['#science','#biology','#education','#shorts'], 'keywords': ['blue carbon'], 'cta': 'Follow for science explained clearly', 'niche': 'science', 'music_style': 'educational ambient', 'thumbnail_concept': 'Educational: ' + 'Blue carbon', 'seo': {'demand': 3, 'evergreen': 5, 'education': 5, 'interest': 3, 'short_form': 5}})

def main():
    deadline = time.time() + BUDGET_MIN * 60
    queue = sorted(TOPICS, key=_seo_score, reverse=True)
    print(f"=== WAVE 6 PREFLIGHT budget={BUDGET_MIN}m topics={len(queue)} ===", flush=True)
    if not has_credential("OPENAI_API_KEY") or not ffmpeg_available():
        raise SystemExit("missing openai or ffmpeg")
    batch_t0 = time.perf_counter(); runs=[]; next_index=900; i=0
    while i < len(queue):
        if deadline - time.time() <= 30:
            print("=== WAVE 6 TIME BUDGET DONE ===", flush=True); break
        wave=[]
        while len(wave) < MAX_WORKERS and i < len(queue):
            wave.append((queue[i], next_index)); i += 1; next_index += 1
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
            futs={pool.submit(run_one, t, idx, len(queue)):(t,idx) for t,idx in wave}
            for fut in as_completed(futs):
                try: runs.append(fut.result())
                except Exception as exc:
                    t,idx=futs[fut]
                    runs.append({"run_index":idx,"topic":t["title"],"asset_id":t["asset_id"],"success":False,"production_error":str(exc),"cost":{"estimated_cost_usd":0}})
        live={"wave":6,"updated_at":datetime.now(timezone.utc).isoformat(),"seconds_remaining":max(0,int(deadline-time.time())),"completed":sum(1 for r in runs if r.get("success")),"attempted":len(runs),"queue_remaining":max(0,len(queue)-i)}
        (REPORT_DIR/"LIVE_BOARD_WAVE6.json").write_text(json.dumps(live,indent=2),encoding="utf-8")
    agg=aggregate(runs, round(time.perf_counter()-batch_t0,2), len(queue)); agg["wave"]=6
    path=REPORT_DIR/"SPRINT_WAVE6_REPORT.json"; path.write_text(json.dumps(agg,indent=2,default=str),encoding="utf-8")
    print("WAVE6 completed", agg["completed_ready_to_post"], "report", path, flush=True)
if __name__ == "__main__":
    main()
