"""Reusable Generational locations — living sets, not empty backdrops."""

from __future__ import annotations

from typing import Any

from services.studio_assets.the_doctor.world import gmri_world_package

_GMRI = gmri_world_package()

LOCATIONS: dict[str, dict[str, Any]] = {
    "LOC-GMRI": {
        "id": _GMRI["id"],
        "name": _GMRI["name"],
        "world_builder_hint": _GMRI.get("world_builder_hint"),
        "architecture": _GMRI["architecture"],
        "lighting": _GMRI["lighting"],
        "palette_hint": _GMRI["palette_hint"],
        "textures": list(_GMRI["textures"]),
        "furniture": list(_GMRI["furniture"]),
        "equipment": list(_GMRI["equipment"]),
        "interactive_props": list(_GMRI["interactive_props"]),
        "ambient_life": list(_GMRI["ambient_life"]),
        "weather": _GMRI["weather"],
        "environmental_animation": list(_GMRI["environmental_animation"]),
        "background_characters": list(_GMRI["background_characters"]),
        "soundscape": list(_GMRI["soundscape"]),
        "detail_dressing": list(_GMRI["detail_dressing"]),
        "domains": list(_GMRI["domains"]),
        "permanent_studio_world": True,
        "owner_character": "CHAR-0001",
        "rooms": list((_GMRI.get("rooms") or {}).keys()),
    },
    "LOC-AI-LAB": {
        "id": "LOC-AI-LAB",
        "name": "AI Research Laboratory",
        "world_builder_hint": "WORLD-AI_LABORATORY",
        "architecture": "glass_and_matte_steel_lab_bays",
        "lighting": "practical_monitor_glow + soft_overhead",
        "palette_hint": "lab",
        "textures": ["brushed_metal", "glass", "cable_trays", "matte_floor"],
        "furniture": ["standing_desks", "server_racks", "whiteboard_wall"],
        "equipment": ["holographic_displays", "gpu_racks", "sensor_arms"],
        "interactive_props": ["floating_diagrams", "stylus_pad", "coffee_thermos"],
        "ambient_life": ["blinking_status_leds", "scrolling_code", "soft_fan_hum_visual"],
        "weather": "interior_climate",
        "environmental_animation": ["monitor_pulse", "dust_motes", "cable_sway"],
        "background_characters": ["researchers_at_stations"],
        "soundscape": ["soft_servers", "keyboard_clicks", "door_hiss"],
        "detail_dressing": ["notes_on_whiteboard", "plant_on_shelf", "running_computers", "sticky_notes"],
        "domains": ["ai", "technology", "computing", "patterns"],
    },
    "LOC-SCIENCE-MUSEUM": {
        "id": "LOC-SCIENCE-MUSEUM",
        "name": "Science Museum",
        "world_builder_hint": "WORLD-MUSEUM",
        "architecture": "high_atrium_with_mezzanine",
        "lighting": "skylight_volumetric + exhibit_spots",
        "palette_hint": "ocean",
        "textures": ["marble", "glass_cases", "wood_rail"],
        "furniture": ["exhibit_plinths", "benches"],
        "equipment": ["interactive_screens", "scale_models"],
        "interactive_props": ["push_button_exhibits", "rotating_globe"],
        "ambient_life": ["visitors_passing", "kid_pointing", "guide_tablet"],
        "weather": "skylight_cloud_drift",
        "environmental_animation": ["rotating_mobile", "exhibit_lights", "dust_in_sunbeams"],
        "background_characters": ["families", "tour_groups"],
        "soundscape": ["soft_crowd", "exhibit_beeps"],
        "detail_dressing": ["museum_labels", "banner_hangings", "gift_shop_preview"],
        "domains": ["science", "general", "education", "history"],
    },
    "LOC-OCEAN-OBSERVATORY": {
        "id": "LOC-OCEAN-OBSERVATORY",
        "name": "Ocean Observatory",
        "world_builder_hint": "WORLD-OCEAN_RESEARCH_OBSERVATORY",
        "architecture": "glass_sphere_over_reef",
        "lighting": "caustic_blue + soft_warm_interior",
        "palette_hint": "ocean",
        "textures": ["wet_glass", "metal_rails", "coral_view"],
        "furniture": ["observation_benches", "instrument_console"],
        "equipment": ["sonar_panels", "dive_camera_feeds"],
        "interactive_props": ["binocular_station", "specimen_tray"],
        "ambient_life": ["fish_schools", "bubbles", "researchers"],
        "weather": "surface_swell_outside",
        "environmental_animation": ["caustics", "kelp_sway", "bubble_rise"],
        "background_characters": ["marine_biologists"],
        "soundscape": ["muffled_waves", "sonar_blip"],
        "detail_dressing": ["tide_charts", "wetsuits_on_hooks", "seaweed_samples"],
        "domains": ["ocean", "biology", "nature", "animals", "exploration"],
    },
    "LOC-SPACE-STATION": {
        "id": "LOC-SPACE-STATION",
        "name": "Space Station",
        "world_builder_hint": "WORLD-OUTER_SPACE",
        "architecture": "modular_ring_corridor",
        "lighting": "cool_practicals + earthshine",
        "palette_hint": "night",
        "textures": ["padded_panels", "viewport_glass", "alloy"],
        "furniture": ["zero_g_handholds", "console_bay"],
        "equipment": ["life_support", "observation_array"],
        "interactive_props": ["tablet_clip", "floating_tool"],
        "ambient_life": ["status_lights", "crew_drift"],
        "weather": "starfield_outside",
        "environmental_animation": ["star_drift", "panel_blink", "earth_rotation"],
        "background_characters": ["crew_members"],
        "soundscape": ["hvac_hum", "radio_static_soft"],
        "detail_dressing": ["mission_patches", "checklist_clipboard", "plant_bag"],
        "domains": ["space", "physics", "technology", "exploration"],
    },
    "LOC-ANCIENT-LIBRARY": {
        "id": "LOC-ANCIENT-LIBRARY",
        "name": "Ancient Library",
        "world_builder_hint": "WORLD-LIBRARY",
        "architecture": "vaulted_stacks_and_galleries",
        "lighting": "warm_lamps + high_window_god_rays",
        "palette_hint": "gold",
        "textures": ["aged_paper", "oak", "stone"],
        "furniture": ["reading_tables", "ladders", "globes"],
        "equipment": ["manuscript_stands", "magnifiers"],
        "interactive_props": ["open_tome", "inkwell", "map_scroll"],
        "ambient_life": ["page_turn", "dust_motes", "distant_scholars"],
        "weather": "rain_on_tall_windows",
        "environmental_animation": ["candle_flicker", "curtain_sway", "dust_drift"],
        "background_characters": ["scholars"],
        "soundscape": ["quiet_pages", "soft_rain"],
        "detail_dressing": ["books_on_shelves", "notes", "wax_seal", "ladder"],
        "domains": ["history", "folklore", "literature", "philosophy", "mythology"],
    },
    "LOC-MEDICAL-RESEARCH": {
        "id": "LOC-MEDICAL-RESEARCH",
        "name": "Medical Research Center",
        "world_builder_hint": "WORLD-HOSPITAL",
        "architecture": "clean_lab_wing",
        "lighting": "cool_clinical + soft_fill",
        "palette_hint": "lab",
        "textures": ["white_tile", "glass", "steel"],
        "furniture": ["exam_benches", "lab_stools"],
        "equipment": ["microscopes", "monitors", "centrifuge"],
        "interactive_props": ["sample_slides", "chart_boards"],
        "ambient_life": ["monitor_waveforms", "staff_passing"],
        "weather": "interior",
        "environmental_animation": ["waveform_pulse", "sterile_light_hum"],
        "background_characters": ["clinicians"],
        "soundscape": ["soft_beeps", "shoe_squeaks"],
        "detail_dressing": ["charts", "gloves", "hand_sanitizer", "plants"],
        "domains": ["medicine", "biology", "health", "anatomy"],
    },
    "LOC-ENGINEERING-WORKSHOP": {
        "id": "LOC-ENGINEERING-WORKSHOP",
        "name": "Engineering Workshop",
        "world_builder_hint": "WORLD-FACTORY",
        "architecture": "open_bay_with_mezzanine",
        "lighting": "practical_work_lamps + window_daylight",
        "palette_hint": "gold",
        "textures": ["concrete", "steel", "wood_benches"],
        "furniture": ["workbenches", "parts_bins"],
        "equipment": ["cnc", "3d_printers", "tool_walls"],
        "interactive_props": ["blueprint_rolls", "prototype_parts"],
        "ambient_life": ["sparks", "printers_moving"],
        "weather": "interior_with_open_bay_breeze",
        "environmental_animation": ["belt_motion", "printer_head", "dust"],
        "background_characters": ["technicians"],
        "soundscape": ["tools", "compressors"],
        "detail_dressing": ["blueprints", "coffee_cups", "labeled_bins", "safety_posters"],
        "domains": ["engineering", "infrastructure", "mechanics", "invention", "physics"],
    },
    "LOC-RAINFOREST-CAMP": {
        "id": "LOC-RAINFOREST-CAMP",
        "name": "Rainforest Research Camp",
        "world_builder_hint": "WORLD-RAINFOREST",
        "architecture": "raised_tents_and_observation_deck",
        "lighting": "canopy_dappled_sun + warm_lanterns",
        "palette_hint": "ireland",
        "textures": ["wet_wood", "canvas", "leaf_litter"],
        "furniture": ["camp_tables", "hammocks"],
        "equipment": ["field_kits", "camera_traps"],
        "interactive_props": ["specimen_jars", "field_notebook"],
        "ambient_life": ["insects", "birds", "leaves"],
        "weather": "mist_after_rain",
        "environmental_animation": ["leaf_sway", "mist_roll", "insect_drift"],
        "background_characters": ["field_researchers"],
        "soundscape": ["raindrops", "insects", "distant_birds"],
        "detail_dressing": ["boots", "maps", "hanging_plants", "water_bottles"],
        "domains": ["nature", "biology", "ecology", "animals", "climate"],
    },
    "LOC-FUTURE-CITY": {
        "id": "LOC-FUTURE-CITY",
        "name": "Future City",
        "world_builder_hint": "WORLD-FUTURE_CITY",
        "architecture": "vertical_plazas_and_transit_spines",
        "lighting": "neon_rim + soft_daylight",
        "palette_hint": "night",
        "textures": ["glass", "composites", "light_strips"],
        "furniture": ["plaza_seating", "kiosks"],
        "equipment": ["transit_pods", "holo_signs"],
        "interactive_props": ["public_info_pillar"],
        "ambient_life": ["traffic", "pedestrians", "drones"],
        "weather": "clear_haze",
        "environmental_animation": ["traffic_band", "sign_scroll", "drone_pass"],
        "background_characters": ["citizens"],
        "soundscape": ["distant_transit", "crowd_murmur"],
        "detail_dressing": ["billboards", "planters", "chargers"],
        "domains": ["technology", "future", "urban", "society", "ai"],
    },
    "LOC-HISTORICAL-VILLAGE": {
        "id": "LOC-HISTORICAL-VILLAGE",
        "name": "Historical Village",
        "world_builder_hint": "WORLD-MEDIEVAL_VILLAGE",
        "architecture": "timber_and_stone_lanes",
        "lighting": "golden_hour + hearth_glow",
        "palette_hint": "gold",
        "textures": ["thatch", "cobble", "timber"],
        "furniture": ["market_stalls", "benches"],
        "equipment": ["well", "carts"],
        "interactive_props": ["market_goods", "signboard"],
        "ambient_life": ["villagers", "livestock", "smoke"],
        "weather": "soft_wind",
        "environmental_animation": ["flags", "smoke_drift", "leaf_fall"],
        "background_characters": ["villagers"],
        "soundscape": ["market", "wind", "chickens"],
        "detail_dressing": ["barrels", "lanterns", "hanging_herbs"],
        "domains": ["history", "folklore", "mythology", "culture"],
    },
}


def list_locations() -> list[dict[str, Any]]:
    return [dict(v) for v in LOCATIONS.values()]


def get_location(location_id: str) -> dict[str, Any] | None:
    row = LOCATIONS.get(str(location_id or "").upper())
    return dict(row) if row else None
