"""Permanent cast definitions — identity templates for the Character Library."""

from __future__ import annotations

from typing import Any

CAST_DEFINITIONS: dict[str, dict[str, Any]] = {
    "DOCTOR_001": {
        "canonical_name": "The Doctor",
        "role": "canonical_medical_educator",
        "age_appearance": "adult_ageless_cyborg",
        "body_type": "athletic_approachable_humanoid",
        "height_cm": 185,
        "proportions": "hero_educator_canonical",
        "continuity_version": "1.1.0",
        "personality": [
            "highly_intelligent",
            "patient",
            "curious",
            "optimistic",
            "encouraging",
            "evidence_driven",
            "compassionate",
        ],
        "wardrobe_outfits": ["lab_coat", "research_attire", "casual_clothing", "emergency_gear"],
        "default_outfit": "lab_coat",
        "voice_ref": "VOICE-THE-DOCTOR-001",
        "studio_asset_path": "data/studio_assets/DOCTOR_001/",
        "is_gold_standard": True,
        "status": "permanent",
        "compose_existing_asset": True,
    },
    "FOUNDER_001": {
        "canonical_name": "The Founder",
        "role": "inspiration_traveler_host",
        "age_appearance": "adult_mid_thirties",
        "body_type": "athletic_grounded_traveler",
        "height_cm": 180,
        "proportions": "cinematic_everyman_hero",
        "continuity_version": "1.0.0",
        "personality": [
            "reflective",
            "warm",
            "determined",
            "curious",
            "humble_authority",
        ],
        "wardrobe_outfits": ["travel_coat", "casual_layer", "formal_address"],
        "default_outfit": "travel_coat",
        "voice_ref": "VOICE-0001",
        "studio_asset_path": "data/studio_assets/FOUNDER_001/",
        "is_gold_standard": False,
        "status": "permanent",
        "compose_existing_asset": False,
    },
    "TEACHER_001": {
        "canonical_name": "The Teacher",
        "role": "classroom_educator",
        "age_appearance": "adult_forties",
        "body_type": "approachable_average",
        "height_cm": 172,
        "proportions": "warm_educator",
        "continuity_version": "0.1.0",
        "personality": ["patient", "clear", "encouraging", "curious"],
        "wardrobe_outfits": ["classroom_attire", "field_trip_layers"],
        "default_outfit": "classroom_attire",
        "voice_ref": None,
        "studio_asset_path": "data/studio_assets/TEACHER_001/",
        "status": "reserved",
        "compose_existing_asset": False,
    },
    "HISTORIAN_001": {
        "canonical_name": "The Historian",
        "role": "history_storyteller",
        "age_appearance": "adult_fifties",
        "body_type": "slender_scholar",
        "height_cm": 176,
        "proportions": "scholar_presence",
        "continuity_version": "0.1.0",
        "personality": ["thoughtful", "precise", "dramatic_when_needed", "warm"],
        "wardrobe_outfits": ["archive_coat", "lecture_attire"],
        "default_outfit": "archive_coat",
        "voice_ref": None,
        "studio_asset_path": "data/studio_assets/HISTORIAN_001/",
        "status": "reserved",
        "compose_existing_asset": False,
    },
    "ENGINEER_001": {
        "canonical_name": "The Engineer",
        "role": "systems_and_invention_host",
        "age_appearance": "adult_thirties",
        "body_type": "practical_athletic",
        "height_cm": 178,
        "proportions": "builder_stance",
        "continuity_version": "0.1.0",
        "personality": ["pragmatic", "inventive", "clear", "energetic"],
        "wardrobe_outfits": ["workshop_gear", "presentation_blazer"],
        "default_outfit": "workshop_gear",
        "voice_ref": None,
        "studio_asset_path": "data/studio_assets/ENGINEER_001/",
        "status": "reserved",
        "compose_existing_asset": False,
    },
    "NURSE_001": {
        "canonical_name": "The Nurse",
        "role": "care_partner_educator",
        "age_appearance": "adult_thirties",
        "body_type": "steady_caregiver",
        "height_cm": 168,
        "proportions": "care_presence",
        "continuity_version": "0.1.0",
        "personality": ["empathetic", "calm", "precise", "reassuring"],
        "wardrobe_outfits": ["clinical_scrubs", "education_coat"],
        "default_outfit": "clinical_scrubs",
        "voice_ref": None,
        "studio_asset_path": "data/studio_assets/NURSE_001/",
        "status": "reserved",
        "compose_existing_asset": False,
    },
    "PATIENT_CHILD_001": {
        "canonical_name": "Patient Child",
        "role": "pediatric_patient_presence",
        "age_appearance": "child_8_to_10",
        "body_type": "child_proportions",
        "height_cm": 132,
        "proportions": "child_canonical",
        "continuity_version": "0.1.0",
        "personality": ["curious", "brave", "sensitive", "playful"],
        "wardrobe_outfits": ["hospital_gown_soft", "everyday_clothes"],
        "default_outfit": "hospital_gown_soft",
        "voice_ref": None,
        "studio_asset_path": "data/studio_assets/PATIENT_CHILD_001/",
        "status": "reserved",
        "compose_existing_asset": False,
        "scale_notes": "Child skeleton scale — joint ranges and gait differ from adult gold standard",
    },
}


def get_cast_definition(character_id: str) -> dict[str, Any] | None:
    return CAST_DEFINITIONS.get(str(character_id or "").upper())


def list_cast_ids() -> list[str]:
    return list(CAST_DEFINITIONS.keys())
