"""Post-Production — Agent 17's intelligent editing layer.

Public surface:
    from services.post_production import build_post_production_package, post_produce_items
"""

from services.post_production.config import (
    CAPTION_THEMES,
    COLOR_PRESETS,
    EDITING_STYLES,
    EXPORT_PRESETS,
    LOUDNESS_TARGETS,
    PACING_PROFILES,
    SUPPORTED_PLATFORMS,
    TRANSITION_STYLES,
    PostProductionConfig,
    configure,
    get_post_production_config,
    reset_post_production_config,
)
from services.post_production.models import (
    AUDIO_MIX_FINAL_FIELDS,
    CAPTION_ENTRY_FIELDS,
    CAPTION_TIMELINE_FIELDS,
    CLIP_FIELDS,
    COLOR_GRADING_FIELDS,
    EDIT_TIMELINE_FIELDS,
    EFFECT_PLAN_FIELDS,
    EXPORT_PRESET_FIELDS,
    MARKER_FIELDS,
    MOTION_GRAPHIC_FIELDS,
    PLATFORM_EXPORT_FIELDS,
    POST_PRODUCTION_ENGINE_VERSION,
    POST_PRODUCTION_PACKAGE_FIELDS,
    POST_PRODUCTION_PACKAGE_VERSION,
    POST_PRODUCTION_SUMMARY_FIELDS,
    PROVIDER_INSTRUCTION_FIELDS,
    PUBLISHING_METADATA_FIELDS,
    QUALITY_ISSUE_FIELDS,
    QUALITY_REPORT_FIELDS,
    SCENE_CUT_FIELDS,
    SUBTITLE_STYLING_FIELDS,
    TRACK_FIELDS,
    TRANSITION_PLAN_FIELDS,
    EditStatus,
    PackageReadiness,
)
from services.post_production.package import (
    build_post_production_package,
    collect_post_production_items,
    post_produce_items,
)

__all__ = [
    "AUDIO_MIX_FINAL_FIELDS",
    "CAPTION_ENTRY_FIELDS",
    "CAPTION_THEMES",
    "CAPTION_TIMELINE_FIELDS",
    "CLIP_FIELDS",
    "COLOR_GRADING_FIELDS",
    "COLOR_PRESETS",
    "EDITING_STYLES",
    "EDIT_TIMELINE_FIELDS",
    "EFFECT_PLAN_FIELDS",
    "EXPORT_PRESET_FIELDS",
    "EXPORT_PRESETS",
    "LOUDNESS_TARGETS",
    "MARKER_FIELDS",
    "MOTION_GRAPHIC_FIELDS",
    "PLATFORM_EXPORT_FIELDS",
    "PACING_PROFILES",
    "POST_PRODUCTION_ENGINE_VERSION",
    "POST_PRODUCTION_PACKAGE_FIELDS",
    "POST_PRODUCTION_PACKAGE_VERSION",
    "POST_PRODUCTION_SUMMARY_FIELDS",
    "PROVIDER_INSTRUCTION_FIELDS",
    "PUBLISHING_METADATA_FIELDS",
    "QUALITY_ISSUE_FIELDS",
    "QUALITY_REPORT_FIELDS",
    "SCENE_CUT_FIELDS",
    "SUBTITLE_STYLING_FIELDS",
    "SUPPORTED_PLATFORMS",
    "TRACK_FIELDS",
    "TRANSITION_PLAN_FIELDS",
    "TRANSITION_STYLES",
    "EditStatus",
    "PackageReadiness",
    "PostProductionConfig",
    "build_post_production_package",
    "collect_post_production_items",
    "configure",
    "get_post_production_config",
    "post_produce_items",
    "reset_post_production_config",
]
